# -*- coding: utf-8 -*-
# The topbar's "Points Spent" headline number blends real + estimated costs
# (colored blue, ~194 instead of 171) when the build includes at least one
# purchased-but-unconfirmed rank with a guess - the ~ prefix and color are
# the only visible cue; the confirmed/estimated breakdown lives in the
# title tooltip only, same hover-to-disclose pattern as every other
# estimate badge in the app (no separate visible note element anymore -
# topbar is glanceable-density territory). Progression's own running total
# blends the exact same way now (it used to stay strictly real while the
# topbar blended, but a cumulative frozen through a step whose own pill
# shows a nonzero ~N estimate read as "the estimate isn't doing anything" -
# see logic.js's computeProgressionSteps for blendedCumulative). What's
# still guaranteed: spentPoints()/affordability math itself never reads a
# guess - "?" still costs exactly 0 there - proven here by the real/
# estimated split staying separately trackable (the "171 confirmed" portion
# of the tooltip) rather than the two numbers ever being silently merged
# into one indistinguishable figure. This is a real shared build with
# several purchased-but-unconfirmed ranks (First Aid, Innate Eminence,
# Improved Mend), independently verified by hand: real total 171, guesses
# add 23, so the headline (and now Progression's own last-row total) should
# read "~194". (Real total climbed from 164 to 171, and estimated dropped
# from 32 to 23, across two separate wiki scrapes that confirmed Combat
# Fury's cost as 1/2/3/4 instead of 1/2/4/6, then Combat Stability's rank 3
# as a real 6 - matching what its own guess had already said - and First
# Aid's rank 2 as a real 1, not the 2 its old guess had said.)
#
# The BUILD code below also happens to be a genuine backward-compatibility
# case: it was generated by an older version of the app, before the
# total-points concept was removed, and still carries a "t" (totalPoints)
# field in its decoded payload - loading it here without error, with
# nothing depending on that field anymore, is itself the regression test
# for "an old share link/save must not break just because a field it used
# to carry stopped being read."
import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
from playwright.sync_api import sync_playwright

BASE = "http://localhost:8743/index.html"
BUILD = "H4sIAAAAAAAACm2QwWrEMAxE_2XOc7DslZz4D3roFxgfQhuWQLotS2gPpf9eZAe2h-InxrY0c9A3PlEi8YJSZ2ZqI3YUDcSBIiEE4o5SqzE11sxLY536XWSIuqlG6a1oFJfMqbEm6S-NvaeJ5qLjc0xaGCkhd52VqTXiA8Vtg2jU9MCCk4Qx_4-HqfrQ6YlUY5QH-TwTJ1ovo8jJrCee00v_0ogv38glEE-37diWHcSxLjt8N4F43l6vy9sK4v2-3K4rWvv5BaiyIJppAQAA"

with sync_playwright() as p:
    browser = p.chromium.launch(channel="chrome", headless=True)
    page = browser.new_page(viewport={"width": 1400, "height": 900})
    errors = []
    page.on("pageerror", lambda exc: errors.append(str(exc)))
    page.on("dialog", lambda d: d.accept())

    # --- Fresh page, nothing purchased: plain real number, red, no note. ---
    page.goto(BASE)
    page.wait_for_selector("#treeWrap .node")
    sv0 = page.locator("#spentValue")
    print("fresh spentValue text/class:", sv0.inner_text(), sv0.get_attribute("class"))
    assert sv0.inner_text() == "0"
    assert sv0.get_attribute("class") is None
    color0 = sv0.evaluate("el => getComputedStyle(el).color")
    assert color0 == "rgb(217, 76, 76)", f"FAIL: expected real 'spent' red, got {color0}"
    assert sv0.get_attribute("title") is None
    print("PASS: no guesses purchased -> plain real number, red, no tooltip")

    # --- Load a build with several purchased-but-unconfirmed ranks. This
    # build code was generated by an older app version and still embeds a
    # "t" (totalPoints) field the app no longer reads at all - loading it
    # without error IS the backward-compatibility check. ---
    errors_before_load = len(errors)
    page.goto(f"{BASE}?build={BUILD}")
    page.wait_for_selector("#treeWrap .node")
    page.wait_for_timeout(200)
    assert len(errors) == errors_before_load, f"FAIL: loading an old build with a stale 't' field threw: {errors}"
    print("PASS: an old build code carrying a stripped-out 't' (totalPoints) field loads without error")

    sv = page.locator("#spentValue")
    print("spentValue text:", sv.inner_text())
    assert sv.inner_text() == "~194"
    assert "is-estimate" in sv.get_attribute("class")
    color = sv.evaluate("el => getComputedStyle(el).color")
    print("spentValue computed color:", color)
    assert color == "rgb(90, 169, 230)", f"FAIL: blended headline should render blue, got {color}"

    title = sv.get_attribute("title")
    print("spentValue title:", title)
    assert title == "171 confirmed + 23 estimated.", f"FAIL: unexpected tooltip text: {title}"
    print("PASS: headline blends to ~194 in blue, full breakdown lives only in the tooltip")

    # --- Progression's own running total now blends the same way the
    # topbar does - the last row's total must match the headline exactly
    # (~194), with the same "171 confirmed + 23 estimated." breakdown in
    # its own tooltip, proving the two displays agree rather than showing
    # two different numbers for the same underlying build. ---
    page.click('button[data-tab="progression"]')
    page.wait_for_timeout(100)
    prog_total_el = page.locator(".progression-row .cost-total").last
    prog_total = prog_total_el.inner_text()
    prog_title = prog_total_el.get_attribute("title")
    print("Progression's blended running total (must match the topbar's ~194):", prog_total, "|", prog_title)
    assert prog_total == "~194 total", f"FAIL: expected Progression's total to blend to ~194 like the topbar, got {prog_total}"
    assert "is-estimate" in prog_total_el.get_attribute("class")
    assert prog_title == "171 confirmed + 23 estimated.", f"FAIL: unexpected breakdown tooltip: {prog_title}"
    print("PASS: Progression's running total blends in estimates exactly like the topbar headline does, agreeing on both the figure and its breakdown")

    # --- Second, independent build: this is the exact scenario the bug was
    # originally reported against - Packrat trained to rank 10, its last 6
    # ranks (5-10) all carrying the same flat "~1" manual guess, mixed in
    # with plenty of real, fully-confirmed ranks earlier in the click
    # order. Real total 193, guesses add 6 (just Packrat's own 6 guessed
    # ranks now - Combat Stability rank 3 used to also be a guess here too,
    # but a wiki scrape confirmed it as a real 6, exactly matching what its
    # own guess had already said, so the blended headline (~199) is
    # unchanged even though the real/estimated split moved), so the
    # headline - and every Progression row from the first guessed step
    # onward - should read "~199". Before the blendedCumulative fix, every
    # one of Packrat's guessed-rank rows showed the SAME frozen total
    # (whatever the real total was at that point), even though each row's
    # own pill showed a nonzero ~1 estimate - a visibly increasing per-step
    # cost next to a cumulative that never moved. ---
    page2 = browser.new_page(viewport={"width": 1400, "height": 900})
    errors2 = []
    page2.on("pageerror", lambda exc: errors2.append(str(exc)))
    BUILD2 = "H4sIAAAAAAAACn2OsQ4CMQxD_yWzh0vStL3-SpWJlQExsCD-HSW9EwwI5UmuJdfJkx40BHShMXc0sDroSsM20J3GnBXqmA3FMXu-hdOIgrfQCg5p6I6pnE5LRtWWrBLdU8qW_03SmaKGrBaOVnfQjUYkTCAVpl8IlCHtNyvTjqk5PScWiCKWn8RZifCHOHJRTuxA9A_-egN0VogmSwEAAA"
    page2.goto(f"{BASE}?build={BUILD2}")
    page2.wait_for_selector("#treeWrap .node")
    page2.wait_for_timeout(200)

    sv2 = page2.locator("#spentValue")
    print("second build spentValue:", sv2.inner_text(), sv2.get_attribute("title"))
    assert sv2.inner_text() == "~199"
    assert sv2.get_attribute("title") == "193 confirmed + 6 estimated."

    page2.click('button[data-tab="progression"]')
    page2.wait_for_timeout(150)
    packrat_rows = page2.locator(".progression-row", has=page2.locator(".step-name", has_text="Packrat"))
    totals = [packrat_rows.nth(i).locator(".cost-total").inner_text() for i in range(packrat_rows.count())]
    print("Packrat rank 1-10's running totals in order:", totals)
    # Ranks 1-4 are Packrat's own real ranks, and now render as PLAIN
    # numbers - Combat Stability rank 3 (a step earlier in the click order)
    # used to be guessed too, but is now confirmed real at exactly the
    # value its own guess already said, so the real cumulative has caught
    # back up to the blended one by the time Packrat's real ranks are
    # reached (no divergence left to show). Ranks 5-10 are each
    # independently guessed and reintroduce the blend from there - every
    # one of the 10 must still show a total exactly 1 higher than the row
    # before it, proving neither Packrat's real ranks nor its guessed ones
    # ever freeze it, regardless of which side of the ~ they land on.
    expected = [f"{n} total" for n in range(190, 194)] + [f"~{n} total" for n in range(194, 200)]
    assert totals == expected, \
        f"FAIL: Packrat's running total must climb by exactly 1 every rank, real or guessed - got {totals}"
    print("PASS: the running total climbs through Packrat's real ranks and its guessed ones alike, never freezing")

    print("ERRORS:", errors2)
    assert not errors2
    page2.close()

    print("ERRORS:", errors)
    assert not errors
    browser.close()
    print("ALL PASS")
