// Pattern-inferred cost estimates for AAs the wiki hasn't documented
// yet, generated by wiki-sync/guess_costs.py - see that script's
// docstring for the actual methodology (cross-referenced sibling AAs,
// never a single AA's own progression alone). DO NOT hand-edit; rerun
// the generator instead, which recomputes this file from scratch every
// time rather than merging - a guess that no longer has corroborating
// evidence (or whose slot got confirmed in data.src.js) simply won't
// reappear.
//
// Keyed exactly like aaIds.js's AA_ID_TABLE (scope:className:key), each
// entry mapping a rank INDEX (as a string, matching that AA's costs
// array position) to a guess. Only ever consulted by the app when the
// real costs[i] is still "?" - keys.js's costGuessFor is the only
// reader, and logic.js only calls that for a rank whose real cost
// string is exactly "?". A guess never substitutes for a real cost in
// spentPoints()/affordability math anywhere - purely a display hint.
export const COST_GUESS_TABLE = {
  "class:Magician:turn-summoned": { "2": { value: 9, confidence: "high", basedOn: ["Acrobatics", "Alchemy Mastery", "Burst of Power", "Critical Affliction", "Double Riposte", "Healing Boon", "Improved Mend", "Instrument Mastery", "Jam Fest", "Quick Damage", "Quick Evacuation", "Rapid Feign", "Singing Mastery", "Slay Undead", "Soul Abrasion", "Weapon Mastery of the Scout"] } }
};
