// Pattern-inferred estimates for the numeric values inside AA effect
// descriptions the wiki hasn't documented yet, generated by
// wiki-sync/guess_effects.py - see that script's docstring for the
// actual methodology. DO NOT hand-edit; rerun the generator instead,
// which recomputes this file from scratch every time rather than
// merging - a guess that no longer has corroborating evidence (or
// whose slot got confirmed in data.src.js) simply won't reappear.
//
// Keyed exactly like aaIds.js's AA_ID_TABLE (scope:className:key), then
// by progression index (order the progression appears in the
// description, as a string) and rank index (also as a string,
// matching that progression's slot position) to a guess. Only ever
// consulted by the app when the real slot text is exactly "?" - a
// guess never substitutes for a real value anywhere descriptions are
// otherwise read (search, export text) - purely a display hint.
export const EFFECT_GUESS_TABLE = {
  "general::combat-fury": { "0": { "1": { value: 3, confidence: "low", basedOn: [], interpolated: true } } }
};
