#!/usr/bin/env python3
"""
Maintains src/aaIds.js — the append-only numeric id table used by the
compact share/export wire format (see exportImport.js's BUILD_CODE and
keys.js's idForKey/entryForId). Run by hand whenever data.src.js changes:

    python wiki-sync/assign_aa_ids.py

For every AA currently in data.src.js, computes the same (scope, className,
key) identity keys.js itself computes (slugified name, with the same
auto-vs-non-auto disambiguation for a repeated name within one category).
Anything already in src/aaIds.js keeps its existing number, unconditionally.
Anything new gets the next unused integer, appended at the end. An id is
NEVER reassigned and NEVER reused, even for an AA that's since been removed
from data.src.js — entries for since-removed AAs are left in the table
rather than deleted, so an old share link's id still means what it always
meant (resolves to "gone", same as an unknown name key does, rather than
risking a future different AA silently inheriting its number).

This mirrors exactly how LEGACY_AA_ORDER in keys.js must never be edited
after the fact - the numbers are a historical record, not a live view.

A wiki RENAME (a typo fix, a capitalization change) looks identical to a
removal from this script's point of view: the old slug's id has nothing
current pointing at it, so it's left behind - but unlike a real removal,
the same AA also gets a brand-new id appended under its new name, and
every share link encoding the old id silently drops that AA from then on.
This can't be told apart from a coincidental removal-and-unrelated-
addition automatically, so it isn't - main() just prints a warning when
an id vanishes in the same run new ones are assigned, prompting a manual
check (the wiki's edit history, same as any other data correction) and,
if it really is a rename, a hand-edit of src/aaIds.js to point the new
key at the OLD id instead of leaving the new one appended.
"""
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import DATA_SRC, DATA_ENTRY_NAME, DATA_ENTRY_AUTO, iter_data_entries, slug_key_for, id_key  # noqa: E402

HERE = Path(__file__).resolve().parent
IDS_FILE = HERE.parent / "src" / "aaIds.js"


def parse_data_src():
    """Returns list of dicts: scope, className, name, auto — in AA_DATA
    order."""
    out = []
    for scope, className, s in iter_data_entries(DATA_SRC):
        nm = DATA_ENTRY_NAME.search(s)
        if not nm:
            continue
        out.append({
            "scope": scope,
            "className": className,
            "name": nm.group(1),
            "auto": bool(DATA_ENTRY_AUTO.search(s)),
        })
    return out


def compute_keys(entries):
    """entries: list of dicts (scope, className, name, auto) in AA_DATA
    order, as returned by parse_data_src. Returns list of
    (scope, className, key), one per entry, using the identity function
    every wiki-sync script shares (see wiki-sync/common.py's slug_key_for -
    the same auto-vs-non-auto disambiguation src/keys.js's keyForEntryIdx
    applies for a repeated name within one (scope, className) bucket)."""
    return [(e["scope"], e["className"], slug_key_for(entries, i)) for i, e in enumerate(entries)]


def load_existing_table():
    if not IDS_FILE.exists():
        return {}
    text = IDS_FILE.read_text(encoding="utf-8")
    m = re.search(r'AA_ID_TABLE\s*=\s*(\{.*?\n\});', text, re.DOTALL)
    if not m:
        raise RuntimeError(f"Could not find AA_ID_TABLE object in {IDS_FILE}")
    # The table is written as valid JSON-ish JS (double-quoted keys, plain
    # integers) - safe to parse as JSON directly.
    obj_text = m.group(1)
    return json.loads(obj_text)


def write_table(table):
    # Sorted by id for a readable diff/history, not that it affects meaning.
    ordered = sorted(table.items(), key=lambda kv: kv[1])
    lines = [f'  "{k}": {v}' for k, v in ordered]
    body = ",\n".join(lines)
    content = (
        "// Append-only numeric id table for every AA, generated by\n"
        "// wiki-sync/assign_aa_ids.py. DO NOT hand-edit the numbers, and\n"
        "// never remove or renumber an existing entry, even for an AA no\n"
        "// longer in data.src.js - see that script's docstring for why.\n"
        "// Consumed by keys.js (idForKey/entryForId), used only by the\n"
        "// compact share/export wire format.\n"
        "export const AA_ID_TABLE = {\n"
        f"{body}\n"
        "};\n"
    )
    # Plain open()+write() rather than Path.write_text(), since write_text's
    # newline= parameter needs Python 3.10+. newline="\n" keeps the
    # working-tree file LF on Windows too - .gitattributes (* text=auto
    # eol=lf) would normalize it on commit either way, but writing it
    # correctly to begin with means git status doesn't show a phantom diff
    # the moment git touches the file.
    with open(IDS_FILE, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)


def compute_vanished(existing, current_id_keys):
    """Ids `existing` still has that no current AA's identity key resolves
    to. A genuine removal is exactly this with no corresponding new id
    assigned in the same run; a rename looks the same on this side, but
    ALSO shows up as a new id, since the renamed AA's new slug doesn't
    match its old table entry and gets appended as if it were a brand-new
    AA. This can't tell those two apart on its own - see main()'s warning."""
    return sorted(k for k in existing if k not in current_id_keys)


def main():
    entries = parse_data_src()
    keyed = compute_keys(entries)
    current_id_keys = {id_key(scope, className, key) for scope, className, key in keyed}

    existing = load_existing_table()
    # Captured before the table is mutated below.
    vanished = compute_vanished(existing, current_id_keys)

    next_id = (max(existing.values()) + 1) if existing else 0

    added = []
    for scope, className, key in keyed:
        ik = id_key(scope, className, key)
        if ik not in existing:
            existing[ik] = next_id
            added.append((ik, next_id))
            next_id += 1

    write_table(existing)

    print(f"Parsed {len(entries)} AA entries from data.src.js")
    print(f"Total ids in table: {len(existing)}")
    if added:
        print(f"Newly assigned ({len(added)}):")
        for ik, i in added:
            print(f"  {i}: {ik}")
    else:
        print("No new AAs since last run - table unchanged.")

    # A rename (not just a removal-and-unrelated-addition) is the one case
    # worth a loud nudge: an id vanishing silently breaks every existing
    # share link for that AA (it resolves to "gone", indistinguishable from
    # a genuine removal - see the module docstring) the moment the SAME AA
    # gets a brand-new id under its new name instead of keeping its old one.
    # This can't disambiguate a real rename from a coincidental remove+add
    # in the same wiki update - that judgment call (check the wiki's edit
    # history, same as any other data correction) is on whoever runs this.
    if vanished and added:
        print()
        print(f"WARNING: {len(vanished)} id(s) present in the table are no longer in data.src.js,")
        print(f"in the same run {len(added)} new id(s) were assigned. If any of these are the")
        print("same AA under a new name (a wiki rename), edit src/aaIds.js by hand to point")
        print("the new key at the OLD id instead of leaving the new one appended, so existing")
        print("share links for that AA keep resolving. If they're unrelated (a genuine removal")
        print("and a genuine addition), no action needed - this is just a heads-up.")
        print(f"Vanished ({len(vanished)}):")
        for ik in vanished:
            print(f"  {existing[ik]}: {ik}")
        print(f"Newly assigned ({len(added)}):")
        for ik, i in added:
            print(f"  {i}: {ik}")


if __name__ == "__main__":
    sys.exit(main())
